// examples/vue-app/src/components/UserList.vue
<script setup lang="ts">
import type { User } from '../api/userApi';
import UserCard from './UserCard.vue';

defineProps<{
  users: User[]
}>()
</script>

<template>
  <div class="user-list">
    <p v-if="users.length === 0">No users found</p>
    <div v-else class="user-grid">
      <UserCard v-for="user in users" :key="user.id" :user="user" />
    </div>
  </div>
</template>

<style scoped>
.user-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  gap: 20px;
}
</style>

// examples/react-app/src/components/UserList.tsx
import { User } from '../store/userStore'
import UserCard from './UserCard'
import './UserList.css'

interface UserListProps {
  users: User[]
}

export default function UserList({ users }: UserListProps) {
  return (
    <div className="user-list">
      <h2>Users ({users.length})</h2>
      <div className="user-grid">
        {users.map((user) => (
          <UserCard key={user.id} user={user} />
        ))}
      </div>
    </div>
  )
}
